/* Autogenerated with kurento-module-creator */

#include "CNVpipeline.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

static std::vector<std::string> hierarchyCNVpipeline;
std::once_flag initFlagCNVpipeline;

static void
initHierarchy ()
{
  hierarchyCNVpipeline.emplace_back("kurento.OpenCVFilter");
  hierarchyCNVpipeline.emplace_back("kurento.Filter");
  hierarchyCNVpipeline.emplace_back("kurento.MediaElement");
  hierarchyCNVpipeline.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
CNVpipeline::getHierarchy () const
{
  std::call_once (initFlagCNVpipeline,initHierarchy);
  return hierarchyCNVpipeline;
}

const std::string&
CNVpipeline::getType () const {
  static std::string typeName = "CNVpipeline";

  return typeName;
}

const std::string&
CNVpipeline::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
CNVpipeline::getModule () const {
  static std::string moduleName =  "cnvpipeline";

  return moduleName;
}

} /* cnvpipeline */
} /* module */
} /* kurento */
