/* Autogenerated with kurento-module-creator */

#ifndef __CNVPIPELINE_IMPL_HPP__
#define __CNVPIPELINE_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "CNVpipeline.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "CNVpipelineOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace cnvpipeline
{
class CNVpipelineImpl;
} /* cnvpipeline */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::cnvpipeline::CNVpipelineImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

class CNVpipelineImpl : public OpenCVFilterImpl, public virtual CNVpipeline, public virtual CNVpipelineOpenCVImpl
{

public:

  CNVpipelineImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~CNVpipelineImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);
  void connectServer(const std::string &server);
  void disconnectServer();
  void addProperty(const std::string &name, const std::string &value);
  void setId(const std::string &id);
private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* cnvpipeline */
} /* module */
} /* kurento */

#endif /*  __CNVPIPELINE_IMPL_HPP__ */
