/* Autogenerated with kurento-module-creator */

#ifndef __CNVPIPELINE_IMPL_FACTORY_HPP__
#define __CNVPIPELINE_IMPL_FACTORY_HPP__

#include "CNVpipelineImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

class CNVpipelineImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  CNVpipelineImplFactory() = default;

  std::string getName() const override {
    return "CNVpipeline";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* cnvpipeline */
} /* module */
} /* kurento */

#endif /*  __CNVPIPELINE_IMPL_FACTORY_HPP__ */
