/* Autogenerated with kurento-module-creator */

#ifndef __CNVPIPELINE_HPP__
#define __CNVPIPELINE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace cnvpipeline
{
class CNVpipeline;
} /* cnvpipeline */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::cnvpipeline::CNVpipeline> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace cnvpipeline
{
class CNVpipeline : public virtual OpenCVFilter
{

public:
  CNVpipeline() = default;
  ~CNVpipeline() override = default;


  virtual void connectServer (const std::string &server) = 0;
  virtual void setToken (const std::string &token) = 0;
  virtual void disconnectServer () = 0;
  virtual void addProperty (const std::string &name, const std::string &value) = 0;
  virtual void setId (const std::string &id) = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* cnvpipeline */
} /* module */
} /* kurento */

#endif /*  __CNVPIPELINE_HPP__ */
