/* Autogenerated with kurento-module-creator */

#ifndef __CNVPIPELINE_OPENCV_IMPL_HPP__
#define __CNVPIPELINE_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "CNVpipeline.hpp"
#include "iorconnectors/PipeConnector.hpp"
#include <EventHandler.hpp>
#include <zmq_addon.hpp>
#include <map>

using namespace std;

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

class CNVpipelineOpenCVImpl : public virtual OpenCVProcess, public ior::PipeConnector
{

public:
  CNVpipelineOpenCVImpl ();
  virtual ~CNVpipelineOpenCVImpl();
  virtual void process (cv::Mat &mat);
  void setId(const std::string &id);
};

} /* cnvpipeline */
} /* module */
} /* kurento */

#endif /*  __CNVPIPELINE_OPENCV_IMPL_HPP__ */
