/* Autogenerated with kurento-module-creator */

#include "CNVpipelineOpenCVImpl.hpp"
#include <KurentoException.hpp>
#include <unistd.h>

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

CNVpipelineOpenCVImpl::CNVpipelineOpenCVImpl (){

}

CNVpipelineOpenCVImpl::~CNVpipelineOpenCVImpl(){
	CNVpipelineOpenCVImpl::disconnectServer();
}


void CNVpipelineOpenCVImpl::setId(const std::string &id){
	CNVpipelineOpenCVImpl::addProperty("id", id);
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */

void CNVpipelineOpenCVImpl::process (cv::Mat &mat){
	send_image(mat);
	cv::cvtColor(receiveImage(), mat, cv::COLOR_BGR2BGRA);
}



} /* cnvpipeline */
} /* module */
} /* kurento */
