/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "CNVpipelineImpl.hpp"
#include "CNVpipelineImplFactory.hpp"
#include "CNVpipelineInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

MediaObjectImpl *CNVpipelineImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  CNVpipelineConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
CNVpipelineImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "connectServer") {
    kurento::JsonSerializer s (false);
    CNVpipelineMethodConnectServer method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<CNVpipeline> (obj) );
    return;
  }

  if (methodName == "disconnectServer") {
    kurento::JsonSerializer s (false);
    CNVpipelineMethodDisconnectServer method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<CNVpipeline> (obj) );
    return;
  }

  if (methodName == "addProperty") {
    kurento::JsonSerializer s (false);
    CNVpipelineMethodAddProperty method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<CNVpipeline> (obj) );
    return;
  }

  if (methodName == "setId") {
    kurento::JsonSerializer s (false);
    CNVpipelineMethodSetId method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<CNVpipeline> (obj) );
    return;
  }

  OpenCVFilterImpl::invoke (obj, methodName, params, response);
}

bool
CNVpipelineImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return OpenCVFilterImpl::connect (eventType, handler);
}

void
CNVpipelineImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'CNVpipelineImpl' cannot be deserialized as an object");
  }
}
} /* cnvpipeline */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::cnvpipeline::CNVpipelineImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::cnvpipeline::CNVpipelineImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::cnvpipeline::CNVpipelineImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::cnvpipeline::CNVpipeline> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::cnvpipeline::CNVpipelineImpl> aux = std::dynamic_pointer_cast<kurento::module::cnvpipeline::CNVpipelineImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::cnvpipeline::CNVpipeline> (aux);
}

} /* kurento */