/* Autogenerated with kurento-module-creator */

#include "CNVpipelineImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace cnvpipeline
{

void dummyCnvpipeline ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<CNVpipeline> object;

    s.SerializeNVP (object);
  }
}

} /* cnvpipeline */
} /* module */
} /* kurento */
